export const quizList =[
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-21'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-21'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-19'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-02'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-07'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-07'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-07'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-07'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-08'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-28'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-30'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-31'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-16'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-10'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-10'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-08'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-11'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-10'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-11'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-14'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-14'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-15'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-12'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-28'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-10'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-08'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-17'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-31'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-30'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-29'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-19'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-02'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-28'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-10'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-13'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-19'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-12'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-11'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-10'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-07'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-15'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-28'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-26'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-11'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-02'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-19'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-21'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-02'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-07'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-08'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-12'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-28'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-27'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-26'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-26'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-27'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-29'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-30'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-30'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-31'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-31'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-27'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-18'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-13'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-14'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-14'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-16'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-08'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-30'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-28'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-28'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-27'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-17'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-17'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-19'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-19'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-26'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-08'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-10'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-10'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-08'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-07'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-14'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-10'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-21'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-18'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-17'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-07'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-14'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-18'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-30'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-31'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-07'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-10'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-12'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-12'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-13'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-15'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-16'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-17'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-30'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-17'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-28'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-15'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-14'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-14'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-12'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-17'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-16'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-08'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-07'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-30'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-29'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-29'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-18'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-17'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-10'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-11'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-08'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-31'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-14'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-18'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-14'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-16'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-17'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-16'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-15'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-07'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-15'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-19'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-17'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-14'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-30'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-18'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-15'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-21'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-21'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-19'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-02'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-21'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-21'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-19'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-02'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-21'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-21'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-19'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-02'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-08-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-08-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-08-04'
    },
]
