export const quizList = [
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-21'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-21'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-19'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-02'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-07'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-07'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-07'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-07'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-28'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-30'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-31'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-16'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-10'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-10'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-11'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-10'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-11'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-14'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-14'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-15'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-12'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-28'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-10'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-17'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-31'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-30'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-29'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-19'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-02'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-28'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-10'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-13'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-19'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-12'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-11'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-10'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-07'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-15'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-28'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-26'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-11'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-02'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-19'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-21'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-02'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-07'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-12'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-28'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-27'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-26'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-26'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-27'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-29'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-30'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-30'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-31'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-31'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-27'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-18'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-13'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-14'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-14'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-16'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-30'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-28'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-28'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-27'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-17'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-17'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-19'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-19'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-26'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-10'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-10'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-07'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-14'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-10'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-21'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-18'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-17'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-07'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-14'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-18'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-30'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-31'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-07'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-06'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-10'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-12'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-12'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-13'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-15'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-16'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-17'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-30'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-17'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-28'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-15'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-14'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-14'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-12'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-17'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-16'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-05'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-07'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-30'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-29'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-29'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-18'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-17'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-10'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-11'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-09'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-31'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-14'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-18'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-14'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-16'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-17'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-16'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-15'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-07'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-15'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-19'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-17'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-14'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-30'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-18'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-15'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-21'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-21'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-19'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-02'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-21'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-21'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-19'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-02'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-25'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-24'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-23'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-21'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-21'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-20'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-19'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-01'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 1,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-02'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 0,
        unansweredNumber: 3,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 1,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 4,
        incorrectNumber: 0,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 2,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-03'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 5,
        incorrectNumber: 0,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 3,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'draw',
        createdAt: '2019-09-22'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 1,
        incorrectNumber: 2,
        unansweredNumber: 2,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 1,
        unansweredNumber: 1,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 2,
        incorrectNumber: 3,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'lost',
        createdAt: '2019-09-04'
    },
    {
        examName: 'YKS',
        courseName: 'Türkçe',
        subjectName: 'Paragrafta Anlam',
        correctNumber: 3,
        incorrectNumber: 2,
        unansweredNumber: 0,
        earnedPoints: '',
        gameResult: 'won',
        createdAt: '2019-09-04'
    }
]
