export const INITIAL_STATE = {
    opponentInformation: {},
    totalRankedWin: 0,
    totalRankedLose: 0,
    totalRankedDraw: 0,
    totalFriendWin: 0,
    totalFriendLose: 0,
    totalFriendDraw: 0,
    totalRankedGames: 0,
    totalFriendGames: 0,
    rankedWinPercentage: 0,
    friendWinPercentage: 0,
    isFriends: false,
    isRequesting: false,
    isRequested: false,
    friendsList: [],
    totalFriendMatchesCount: 0,
    opponentWinCount: 0,
    clientWinCount: 0,
    opponentList: [
        {
            opponentInformation: {name: '', lastname: ''},
            totalRankedWin: 0,
            totalRankedLose: 0,
            totalRankedDraw: 0,
            totalFriendWin: 0,
            totalFriendLose: 0,
            totalFriendDraw: 0,
            totalRankedGames: 0,
            totalFriendGames: 0,
            rankedWinPercentage: 0,
            friendWinPercentage: 0,
            isFriends: false,
            isRequesting: false,
            isRequested: false,
            friendsList: [],
            totalFriendMatchesCount: 0,
            opponentWinCount: 0,
            clientWinCount: 0
        }
    ],
    opponentListLenght: 1
}
