import React from 'react'
import { Scene, Router } from 'react-native-router-flux'
import {
    authScreens,
    gameScreens,
    mainScreens,
    splashScreen,
    tutorialScreen
} from './containers'
import { SCENE_KEYS } from './index'

const RouterComp = () => {
    return (
        <Router>
            <Scene key="root" hideNavBar={true}>
                <Scene key="splash" hideNavBar={true}>
                    <Scene
                        key={SCENE_KEYS.splashScreen}
                        component={splashScreen}
                    />
                </Scene>
                <Scene key="tutorial" hideNavBar={true}>
                    <Scene
                        key={SCENE_KEYS.tutorialScreen}
                        component={tutorialScreen}
                    />
                </Scene>
                <Scene key="auth" hideNavBar={true}>
                    <Scene
                        key={SCENE_KEYS.authScreens.opening}
                        component={authScreens.opening}
                    />
                    <Scene
                        key={SCENE_KEYS.authScreens.login}
                        component={authScreens.login}
                    />
                    <Scene
                        key={SCENE_KEYS.authScreens.register}
                        component={authScreens.register}
                    />
                    <Scene
                        key={SCENE_KEYS.authScreens.resetPassword}
                        component={authScreens.resetPassword}
                    />
                    <Scene
                        key={SCENE_KEYS.authScreens.getInfo}
                        component={authScreens.getInfo}
                    />
                </Scene>
                <Scene key="main" hideNavBar={true}>
                    <Scene
                        key={SCENE_KEYS.mainScreens.main}
                        component={mainScreens.main}
                    />
                    <Scene
                        key={SCENE_KEYS.mainScreens.profile}
                        component={mainScreens.profile}
                    />
                    <Scene
                        key={SCENE_KEYS.mainScreens.profileSearch}
                        component={mainScreens.profileSearch}
                    />
                    <Scene
                        key={SCENE_KEYS.mainScreens.opponentsProfile}
                        component={mainScreens.opponentsProfile}
                    />
                    <Scene
                        key={SCENE_KEYS.mainScreens.settings}
                        component={mainScreens.settings}
                    />
                    <Scene
                        key={SCENE_KEYS.mainScreens.changePassword}
                        component={mainScreens.changePassword}
                    />
                    <Scene
                        key={SCENE_KEYS.mainScreens.favorites}
                        component={mainScreens.favorites}
                    />
                    <Scene
                        key={SCENE_KEYS.mainScreens.friendsList}
                        component={mainScreens.friendsList}
                    />
                    <Scene
                        key={SCENE_KEYS.mainScreens.createGroupRoom}
                        component={mainScreens.createGroupRoom}
                    />
                    <Scene
                        key={SCENE_KEYS.mainScreens.joinGroupRoom}
                        component={mainScreens.joinGroupRoom}
                    />
                    <Scene
                        key={SCENE_KEYS.mainScreens.notifications}
                        component={mainScreens.notifications}
                    />
                    <Scene
                        key={SCENE_KEYS.mainScreens.statistics}
                        component={mainScreens.statistics}
                    />
                    <Scene
                        key={SCENE_KEYS.mainScreens.goals}
                        component={mainScreens.goals}
                    />
                    <Scene
                        key={SCENE_KEYS.mainScreens.jokerReward}
                        component={mainScreens.jokerReward}
                    />
                </Scene>
                <Scene key="game" hideNavBar={true}>
                    <Scene
                        key={SCENE_KEYS.gameScreens.loading}
                        component={gameScreens.loading}
                    />
                    <Scene
                        key={SCENE_KEYS.gameScreens.rankedGame}
                        component={gameScreens.rankedGame}
                    />
                    <Scene
                        key={SCENE_KEYS.gameScreens.groupGame}
                        component={gameScreens.groupGame}
                    />
                    <Scene
                        key={SCENE_KEYS.gameScreens.gameStats}
                        component={gameScreens.gameStats}
                    />
                    <Scene
                        key={SCENE_KEYS.gameScreens.groupGameStats}
                        component={gameScreens.groupGameStats}
                    />
                    <Scene
                        key={SCENE_KEYS.gameScreens.rankedMatchingScreen}
                        component={gameScreens.rankedMatchingScreen}
                    />
                    <Scene
                        key={SCENE_KEYS.gameScreens.friendMatchingScreen}
                        component={gameScreens.friendMatchingScreen}
                    />
                    <Scene
                        key={SCENE_KEYS.gameScreens.friendGame}
                        component={gameScreens.friendGame}
                    />
                    <Scene
                        key={SCENE_KEYS.gameScreens.friendGameStats}
                        component={gameScreens.friendGameStats}
                    />
                    <Scene
                        key={SCENE_KEYS.gameScreens.soloFriendGameScreen}
                        component={gameScreens.soloFriendGameScreen}
                    />
                    <Scene
                        key={SCENE_KEYS.gameScreens.soloModeLoadingScreen}
                        component={gameScreens.soloModeLoadingScreen}
                    />
                    <Scene
                        key={SCENE_KEYS.gameScreens.soloModeGameScreen}
                        component={gameScreens.soloModeGameScreen}
                    />
                    <Scene
                        key={SCENE_KEYS.gameScreens.soloFriendGameStatsScreen}
                        component={gameScreens.soloFriendGameStatsScreen}
                    />
                    <Scene
                        key={SCENE_KEYS.gameScreens.groupLoading}
                        component={gameScreens.groupLoading}
                    />
                    <Scene
                        key={SCENE_KEYS.gameScreens.soloModeGameStats}
                        component={gameScreens.soloModeGameStats}
                    />
                    <Scene
                        key={SCENE_KEYS.gameScreens.unsolvedModeGameScreen}
                        component={gameScreens.unsolvedModeGameScreen}
                    />
                    <Scene
                        key={SCENE_KEYS.gameScreens.unsolvedModeGameStatsScreen}
                        component={gameScreens.unsolvedModeGameStatsScreen}
                    />
                    <Scene
                        key={SCENE_KEYS.gameScreens.unsolvedModeLoadingScreen}
                        component={gameScreens.unsolvedModeLoadingScreen}
                    />
                </Scene>
            </Scene>
        </Router>
    )
}

export { RouterComp }
